### PR TITLE
Fix inaccessible tests

### LINKED ISSUE #29: Inaccessibility is a lie
The `feature_tests/Fortran/accessibility/test_shmem_acc_mem_04_*.f90` unit tests check whether the compiler does _not_ place the following variable in the data or bss segment:
```
real*8            :: remote_dest(2)
```
However, it's totally fine for the compiler to put a program-level variable (i.e. lifetime is the duration of the full program) like this into the data segment and it turns out that ifort does just this.  The `*05*` tests are similar, except the given variable is `ALLOCATABLE`, which is a more reasonable test of inaccessibility.

I considered proposing to move the `*04*` tests to "error" tests, but I don't think they are even valid error tests.  Can we delete them?

### PR DESCRIPTION
**Pull request by jdinan**
Closes #29

### CODE REVIEW

**Comment by jdinan** [comment]
@tonycurtis Ready for you to review.  The '05 tests check out with gfortran and ifort.

**Comment by tonycurtis** [comment]
+1

**Comment by jdinan** [comment]
Not sure what was up with the spelling in my commit messages yesterday.  Ready to merge on my end.  :neckbeard:

**Comment by jdinan** [comment]
@tonycurtis FYI, in case you were expecting me to click "merge" -- I don't have write access, so I'm counting on you to merge once you're happy with the patches.  Thanks!

**Pull request merged**
