### PR TITLE
Bug fixes to the UH tests

### PR DESCRIPTION
**Pull request by jdinan**
Here's an updated PR.  I dropped the patch that removed the Fortran function declarations from #4.

### CODE REVIEW

**Comment by jdinan** [comment]
I've started running the UH feature tests as part of the Sandia SHMEM continuous integration testing.  You can have a look here, if interested to see how it's going: https://travis-ci.org/regrant/sandia-shmem.

Right now, we have to use my fork, but we'd like to switch back to the main UH tests repository.  Let me know if there's anything I can do to help move this PR along

**Comment by swpoole** [comment]
What needs to be done to allow you to switch back to the main UH tests repository?

**Comment by jdinan** [comment]
@swpoole, I think you may have mis-clicked when posting your comment and closed the PR.  I was waiting on someone from UH to review the code contribution and merge the PR into the uh-tests master.  Because of the amount of churn in this PR, a review is understandably going to take some time.

The UH folks are quite busy with other, more urgent matters at the moment, but I did hear from Tony indicating that the contributions are welcome and reviewing them is on his to-do list.  In the meantime, git is a fantastic tool, and it's no trouble for us to run testing off of our fork of the repository.

**Comment by swpoole** [comment]
Sorry. Did not mean to close. Just want to make sure nothing is in your way.

Best wishes
Steve...

**Comment by jdinan** [comment]
@swpoole, is there a button for you to re-open the PR?  Otherwise, I can re-create it, but we'll lose the comments from the thread.

**Comment by swpoole** [comment]
Think this fixes it?

**Comment by jdinan** [comment]
Yes, thanks.

**Comment by swpoole** [comment]
-----BEGIN PGP SIGNED MESSAGE-----
Hash: SHA256

No prob. I fubar'd, I need to un-fubar.

Steve...

On 12/5/15 10:22, James Dinan wrote:

> Yes, thanks. > > --- > Reply to this email directly or view it on GitHub: >
> https://github.com/openshmem-org/tests-uh/pull/5#issuecomment-162212082

-----BEGIN PGP SIGNATURE-----
Comment: GPGTools - http://gpgtools.org

iQIcBAEBCAAGBQJWYwKJAAoJECiO+w6Set8uMysP/0uhk0pUWMw9Lba5yXkx453L
Zkd6/VKKEK4q15QJll7cJcIRClmQZNDKaMgT9L/VJ0enBxN8QH5TAk2ydT6XkqRx
P4r7SrZ5Jj8N4Xb+D9QGnoVXAp+hOUSZY3GUvceIEs3+5EfGGcOgjoS+s0VH2mOX
5fYFxTf8xjU8PL6Mzi+vQ8HFgYhziTPqwOc1dGPJ81E7JJPoC+HFYysYn65sR+o+
QIx8+hQeYljyhSwR5O1EyGmY1zh2cqcQtmDX4Hnf76BnspSbMZ1v5GdrZKovXck4
GJjRyp6+9IZrsGjUyX6AN9uOcog8Mp5sx/SWidjFPRTRb+TFsGquzJHc6+Ydn9EC
otlQ6ApFrR60VStBOJwG6chypBZwM+N2VGYzKBXB/n3GB0up+yV3Y3W11hXhrgb5
DJ7dVvsoAtISqDfXigYuGADbUDJBqBLFpRt9ZdfXjhUqNE8BdNhSubwXhyUAR/lC
Q1RbBUZd0tw8/SlsoIv8RoHQoNCdObQMMWLSm0rHpDYTHWn00a6zOkLTYEqQ0+j2
BMjuS2RK8F7UMVkihenu0JrePZwmmOGj0Z4dQ/KJfp/N3XQsvlFbpjq+lpZSx8GA
yT7IUEh3YVkU2v0lFgaDkfrug7FxwT+jO5dp4ND9f+mirnyyKwu8D//yT3N3Lbii
lc1ODyRrG/SVpxstxxNN
=722H
-----END PGP SIGNATURE-----

**Pull request merged**
